-- Consulta 1 Total de Veículos Ativos por Tipo

SELECT 
	A.DS_TIPOVEICULO,
	COUNT(B.ID_VEICULO) AS QT_VEICULO

FROM TIPO_VEICULO A
LEFT JOIN VEICULO B ON A.CD_TIPOVEICULO = B.CD_TIPOVEICULO
WHERE B.IN_ATIVO = 'T'
GROUP BY A.DS_TIPOVEICULO;

-- Consulta 2 Total de Motoristas Ativos por Cargo
SELECT 
	A.DS_CARGO,
	COUNT(NR_MOTORISTA) AS QT_MOTORISTA
FROM CARGO_MOTORISTA A 
LEFT JOIN MOTORISTA B ON A.CD_CARGO = B.CD_CARGO
WHERE IN_ATIVO = 'T'
GROUP BY A.DS_CARGO;

-- Consulta 3 Total de abastecimentos por posto conveniado, tipo de combustível por mês e ano

SELECT 
	TO_DATE('01/'||TO_CHAR(DT_ABASTECIMENTO,'MM/RRRR'),'DD/MM/RRRR') AS DT_MOVTO,
	C.NM_PESSOA AS NM_POSTO,
	C.DS_TIPOCOMBUSTIVEL,
	SUM(QT_LITROS) AS QT_LITROS,
	SUM(VL_COMBUSTIVEL) AS VL_COMBUSTIVEL
FROM ABASTECIMENTO A 
INNER JOIN POSTO_CONVENIADO B ON A.CD_POSTO = B.CD_POSTO
INNER JOIN TIPO_COMBUSTIVEL C ON A.CD_TIPOCOMBUSTIVEL = C.CD_COMBUSTIVEL
INNER JOIN PESSOA			D ON B.CD_POSTO = D.ID_PESSOA
GROUP BY TO_DATE('01/||'TO_CHAR(DT_ABASTECIMENTO,'MM/RRRR'),'DD/MM/RRRR'),
	C.NM_PESSOA ,C.DS_TIPOCOMBUSTIVEL;

-- Consulta 4 Total de veículos por unidade atual e tipo de veiculo

SELECT 
	E.NM_PESSOA AS NM_UNIDADE,
	D.DS_TIPOVEICULO,
	COUNT(ID_VEICULO) AS QT_VEICULO
	
FROM UNIDADE_VEICULO A 
INNER JOIN VEICULO B ON A.ID_VEICULO = B.ID_VEICULO
INNER JOIN UNIDADE C ON A.CD_UNIDADE = B.CD_UNIDADE
INNER JOIN TIPO_VEICULO D ON B.CD_TIPOVEICULO = D.CD_TIPOVEICULO
INNER JOIN PESSOA		E ON C.CD_UNIDADE = E.ID_PESSOA
WHERE B.IN_ATIVO = 'T' AND A.DT_DESVINCULO IS NULL
GROUP BY E.NM_PESSOA, D.DS_TIPOVEICULO;

-- Consulta 5 Total de abastecimentos por motorista, mês e ano

SELECT 
	TO_DATE('01/'|| TO_CHAR(DT_ABASTECIMENTO,'MM/RRRR'),'DD/MM/RRRR') AS DT_MOVTO,
	A.CD_MOTORISTA,
	C.NM_PESSOA AS NM_MOTORISTA,
	SUM(A.QT_LITROS),
	SUM(A.VL_COMBUSTIVEL)
FROM ABASTECIMENTO A 
INNER JOIN MOTORISTA B ON A.CD_MOTORISTA = B.NR_MATRICULA
INNER JOIN PESSOA C ON B.NR_MATRICULA = C.ID_PESSOA
GROUP BY TO_DATE('01/'||TO_CHAR(DT_ABASTECIMENTO,'MM/RRRR'),'DD/MM/RRRR') AS DT_MOVTO,
	A.CD_MOTORISTA,	C.NM_PESSOA;


-- Consulta 6 Total de abastecimentos por veículo, tipo de combustivel, mês e ano
SELECT 
	TO_DATE('01/'||TO_CHAR(DT_ABASTECIMENTO,'MM/RRRR'),'DD/MM/RRRR') AS DT_MOVTO,
	A.ID_VEICULO,
	B.DS_TIPOCOMBUSTIVEL,
	SUM(A.QT_LITROS),
	SUM(A.VL_COMBUSTIVEL)
FROM ABASTECIMENTO A 
INNER JOIN TIPO_COMBUSTIVEL B ON A.CD_TIPOCOMBUSTIVEL= B.CD_TIPOCOMBUSTIVEL
GROUP BY TO_DATE('01/'||TO_CHAR(DT_ABASTECIMENTO,'MM/RRRR'),'DD/MM/RRRR'),
A.ID_VEICULO,B.DS_TIPOCOMBUSTIVEL;

-- Consulta 7 Alocação de motoristas e veículos atual
SELECT 
	A.ID_VEICULO,
	A.CD_MOTORISTA,
	C.NM_PESSOA AS NM_MOTORISTA,
	A.DT_VINCULO
FROM VEICULO_MOTORISTA A 
INNER JOIN MOTORISTA B ON A.CD_MOTORISTA = B.NR_MATRICULA
INNER JOIN PESSOA C 	ON B.NR_MATRICULA = C.ID_PESSOA
WHERE DT_DESVINCULO IS NOT NULL;

-- Consulta 8 Quilometragem Rodada por Veículo

SELECT
    A.DT_ABASTECIMENTO,
    A.ID_VEICULO,
    A.NR_HODOMETRO,
    LAG(A.NR_HODOMETRO) OVER (PARTITION BY A.ID_VEICULO ORDER BY A.DT_ABASTECIMENTO) AS NR_HODOMANT,
    A.NR_HODOMETRO - LAG(A.NR_HODOMETRO) OVER (PARTITION BY A.ID_VEICULO ORDER BY A.DT_ABASTECIMENTO) AS QT_KMRODADO
FROM 
    ABASTECIMENTO A


-- Consulta 9 Média Km por Litro por Veiculo

SELECT 
	A.ID_VEICULO,
	SUM(K.QT_KMRODADO) AS QT_KMRODADO,
	SUM(A.QT_LITROS) AS QT_LITROS,
	SUM(K.QT_KMRODADO)/SUM(A.QT_LITROS) AS VL_MEDIAKMLITRO

FROM ABASTECIMENTO A 
INNER JOIN 
		(SELECT
			A.DT_ABASTECIMENTO,
			A.ID_VEICULO,
			A.NR_HODOMETRO,
			LAG(A.NR_HODOMETRO) OVER (PARTITION BY A.ID_VEICULO ORDER BY A.DT_ABASTECIMENTO) AS NR_HODOMANT,
			A.NR_HODOMETRO - LAG(A.NR_HODOMETRO) OVER (PARTITION BY A.ID_VEICULO ORDER BY A.DT_ABASTECIMENTO) AS QT_KMRODADO
		FROM ABASTECIMENTO A) K 
ON A.ID_VEICULO = K.ID_VEICULO


-- Consulta 10 Média de Km/Litro por Veículo, Tipo de Combustivel, Tipo de Veículo Mês e Ano

SELECT 
	TO_DATE('01/'||TO_CHAR(DT_ABASTECIMENTO,'MM/RRRR'),'DD/MM/RRRR') AS DT_MOVTO,
	A.ID_VEICULO,
	B.DS_TIPOVEICULO,
	DS_TIPOCOMBUSTIVEL,
	SUM(KM.QT_KMRODADO) AS QT_KMRODADO,
	SUM(A.QT_LITROS) AS QT_LITROS,
	SUM(KM.QT_KMRODADO) / SUM(A.QT_LITROS) AS QT_MEDIAKMLITRO
FROM ABASTECIMENTO A 
INNER JOIN TIPO_VEICULO B ON A.CD_TIPOVEICULO = B.CD_TIPOVEICULO
INNER JOIN TIPO_COMBUSTIVEL C ON A.CD_TIPOCOMBUSTIVEL = C.TIPO_COMBUSTIVEL
INNER JOIN 
			(SELECT
				A.DT_ABASTECIMENTO,
				A.ID_VEICULO,
				A.NR_HODOMETRO,
				LAG(A.NR_HODOMETRO) OVER (PARTITION BY A.ID_VEICULO ORDER BY A.DT_ABASTECIMENTO) AS NR_HODOMANT,
				A.NR_HODOMETRO - LAG(A.NR_HODOMETRO) OVER (PARTITION BY A.ID_VEICULO ORDER BY A.DT_ABASTECIMENTO) AS QT_KMRODADO
			FROM ABASTECIMENTO A) KM ON A.ID_VEICULO = KM.ID_VEICULO
									    AND TO_DATE('01/'||TO_CHAR(A.DT_ABASTECIMENTO,'MM/RRRR'),'DD/MM/RRRR') = 
											TO_DATE('01/'||TO_CHAR(KM.DT_ABASTECIMENTO,'MM/RRRR'),'DD/MM/RRRR')
GROUP BY TO_DATE('01/||'TO_CHAR(DT_ABASTECIMENTO,'MM/RRRR'),'DD/MM/RRRR') ,
	A.ID_VEICULO,	B.DS_TIPOVEICULO,	DS_TIPOCOMBUSTIVEL	;										
